workflows:
  flutter-app-workflow:
    name: Flutter App Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      # Test step removed
      - name: Build Android
        script: flutter build apk --release
        - name: Build iOS
    script: |
      flutter build ios --release --no-codesign
      xcodebuild -archivePath build/ios/iphoneos/Runner.xcarchive -exportArchive -exportOptionsPlist path/to/your/ExportOptions.plist -exportPath $FCI_BUILD_DIR/build/ios/ipa
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa